// Sample data for the first-run wizard (PLAN.md Q10, sub-task 16): a realistic small-shop catalogue
// the owner can click around in before entering real data. Every row is written with is_sample = 1 so
// "clear sample data" can remove exactly these rows (server/src/modules/seed/service.ts).
//
// This is data only — no database access. Prices are plausible Thai retail prices at the time of
// writing and WILL go stale (risk R15); they are labelled as samples in the UI and can be cleared.
// Money is integer satang, written as <baht>_<satang> (6_890_00 = 6,890.00 baht).

import type { CategoryKind, ProductCondition, TagColor, WarrantyType } from '@pcshop/shared';

export interface SampleSupplier {
  name: string;
  contactName: string;
  phone: string;
  lineId: string;
  /** Invoice number of the one sample goods receipt from this supplier. */
  invoiceNo: string;
  /** How many days before "now" that receipt was recorded. */
  daysAgo: number;
}

/** Names carry "(ตัวอย่าง)" so a sample supplier is never mistaken for a real one. */
export const SAMPLE_SUPPLIERS: SampleSupplier[] = [
  {
    name: 'บจก. ทีเอ็นซี ดิสทริบิวชั่น (ตัวอย่าง)',
    contactName: 'คุณนภา ฝ่ายขาย',
    phone: '02-111-2233',
    lineId: '@tnc-sample',
    invoiceNo: 'INV-SAMPLE-1001',
    daysAgo: 21,
  },
  {
    name: 'บจก. สยามไอที ซัพพลาย (ตัวอย่าง)',
    contactName: 'คุณวิรัตน์',
    phone: '02-444-5566',
    lineId: '@siamit-sample',
    invoiceNo: 'INV-SAMPLE-2087',
    daysAgo: 14,
  },
  {
    name: 'ร้านอะไหล่คอมพิวเตอร์ เชียงใหม่ (ตัวอย่าง)',
    contactName: 'คุณเอ',
    phone: '053-123-456',
    lineId: '@cmparts-sample',
    invoiceNo: 'INV-SAMPLE-334',
    daysAgo: 7,
  },
  {
    name: 'บจก. เกมมิ่งเกียร์ อิมพอร์ต (ตัวอย่าง)',
    contactName: 'คุณพร',
    phone: '02-777-8899',
    lineId: '@gg-sample',
    invoiceNo: 'INV-SAMPLE-5512',
    daysAgo: 3,
  },
];

export interface SampleTag {
  name: string;
  color: TagColor;
}

export const SAMPLE_TAGS: SampleTag[] = [
  { name: 'ขายดี', color: 'green' },
  { name: 'สินค้าโชว์', color: 'blue' },
  { name: 'กล่องไม่สวย', color: 'amber' },
  { name: 'มือสองสภาพดี', color: 'violet' },
];

export interface SampleProduct {
  sku: string;
  name: string;
  brand: string;
  kind: CategoryKind;
  barcode?: string;
  /** Defaults to 'new'. */
  condition?: ProductCondition;
  warrantyType: WarrantyType;
  warrantyMonths: number;
  /** Warranty the supplier gives the shop; defaults to warrantyMonths. */
  supplierWarrantyMonths?: number;
  /** null = "awaiting price": the product exists but can't be sold. */
  priceSatang: number | null;
  /** Set (and above priceSatang) to show a "-X%" discount badge. */
  regularPriceSatang?: number;
  costSatang: number;
  /** Defaults to true; false for services. */
  trackStock?: boolean;
  serialRequired?: boolean;
  minStock?: number;
  /** Quantity the sample goods receipt brings in. 0 = out of stock on purpose. */
  qty: number;
  /** Index into SAMPLE_SUPPLIERS: whose receipt brings this product in. */
  supplier: number;
  specs?: Record<string, unknown>;
  description?: string;
  /** Names from SAMPLE_TAGS. */
  tags?: string[];
}

const D = 'distributor' satisfies WarrantyType;
const SHOP = 'shop' satisfies WarrantyType;
const NONE = 'none' satisfies WarrantyType;

/**
 * ~59 products across all twelve category kinds, including discounted, used, serial-tracked,
 * out-of-stock, low-stock, service (no stock) and one "awaiting price" item, so every automatic tag,
 * filter and badge has something to show.
 */
export const SAMPLE_PRODUCTS: SampleProduct[] = [
  // ---------- CPU (serial-tracked) ----------
  {
    sku: 'CPU-0001',
    name: 'AMD Ryzen 5 7600',
    brand: 'AMD',
    kind: 'cpu',
    barcode: '8850001000017',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 6_890_00,
    costSatang: 6_100_00,
    serialRequired: true,
    minStock: 2,
    qty: 4,
    supplier: 0,
    specs: {
      socket: 'AM5',
      cores: 6,
      threads: 12,
      baseClockGhz: 3.8,
      boostClockGhz: 5.1,
      tdpWatt: 65,
      memoryTypes: ['DDR5'],
      integratedGraphics: true,
    },
    description: 'ซีพียู 6 คอร์ 12 เธรด คุ้มค่าสำหรับเครื่องเล่นเกมระดับกลาง มีการ์ดจอในตัว',
    tags: ['ขายดี'],
  },
  {
    sku: 'CPU-0002',
    name: 'AMD Ryzen 7 7800X3D',
    brand: 'AMD',
    kind: 'cpu',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 13_900_00,
    costSatang: 12_600_00,
    serialRequired: true,
    minStock: 1,
    qty: 2,
    supplier: 0,
    specs: {
      socket: 'AM5',
      cores: 8,
      threads: 16,
      baseClockGhz: 4.2,
      boostClockGhz: 5,
      tdpWatt: 120,
      memoryTypes: ['DDR5'],
      integratedGraphics: true,
    },
    description: 'ซีพียูเล่นเกมแรงที่สุดในรุ่น พร้อมแคช 3D V-Cache',
    tags: ['ขายดี'],
  },
  {
    sku: 'CPU-0003',
    name: 'AMD Ryzen 5 5600',
    brand: 'AMD',
    kind: 'cpu',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 3_690_00,
    regularPriceSatang: 3_990_00,
    costSatang: 3_200_00,
    serialRequired: true,
    minStock: 2,
    qty: 6,
    supplier: 0,
    specs: {
      socket: 'AM4',
      cores: 6,
      threads: 12,
      baseClockGhz: 3.5,
      boostClockGhz: 4.4,
      tdpWatt: 65,
      memoryTypes: ['DDR4'],
      integratedGraphics: false,
    },
  },
  {
    sku: 'CPU-0004',
    name: 'Intel Core i5-14400F',
    brand: 'Intel',
    kind: 'cpu',
    barcode: '8850001000024',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 6_290_00,
    costSatang: 5_700_00,
    serialRequired: true,
    minStock: 2,
    qty: 5,
    supplier: 0,
    specs: {
      socket: 'LGA1700',
      cores: 10,
      threads: 16,
      baseClockGhz: 2.5,
      boostClockGhz: 4.7,
      tdpWatt: 65,
      memoryTypes: ['DDR4', 'DDR5'],
      integratedGraphics: false,
    },
  },
  {
    sku: 'CPU-0005',
    name: 'Intel Core i7-14700K',
    brand: 'Intel',
    kind: 'cpu',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 14_500_00,
    costSatang: 13_200_00,
    serialRequired: true,
    minStock: 1,
    qty: 0,
    supplier: 0,
    specs: {
      socket: 'LGA1700',
      cores: 20,
      threads: 28,
      baseClockGhz: 3.4,
      boostClockGhz: 5.6,
      tdpWatt: 125,
      memoryTypes: ['DDR4', 'DDR5'],
      integratedGraphics: true,
    },
    description: 'ของหมด สั่งเข้าได้ภายใน 3-5 วัน',
  },
  {
    sku: 'CPU-0006',
    name: 'Intel Core i3-12100F (มือสอง)',
    brand: 'Intel',
    kind: 'cpu',
    condition: 'used',
    warrantyType: SHOP,
    warrantyMonths: 3,
    supplierWarrantyMonths: 0,
    priceSatang: 1_990_00,
    costSatang: 1_500_00,
    serialRequired: true,
    minStock: 1,
    qty: 2,
    supplier: 2,
    specs: {
      socket: 'LGA1700',
      cores: 4,
      threads: 8,
      baseClockGhz: 3.3,
      boostClockGhz: 4.3,
      tdpWatt: 58,
      memoryTypes: ['DDR4', 'DDR5'],
      integratedGraphics: false,
    },
    description: 'ถอดจากเครื่องลูกค้า ทดสอบแล้วใช้งานได้ปกติ',
    tags: ['มือสองสภาพดี'],
  },

  // ---------- Mainboard (serial-tracked) ----------
  {
    sku: 'MB-0001',
    name: 'ASUS PRIME B650M-A WIFI',
    brand: 'ASUS',
    kind: 'mainboard',
    barcode: '8850002000015',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 4_990_00,
    costSatang: 4_400_00,
    serialRequired: true,
    minStock: 2,
    qty: 3,
    supplier: 0,
    specs: {
      socket: 'AM5',
      chipset: 'B650',
      formFactor: 'Micro-ATX',
      ramType: 'DDR5',
      ramSlots: 4,
      maxRamGb: 192,
      m2Slots: 2,
      wifi: true,
    },
  },
  {
    sku: 'MB-0002',
    name: 'MSI PRO B760M-A WIFI DDR4',
    brand: 'MSI',
    kind: 'mainboard',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 3_890_00,
    costSatang: 3_400_00,
    serialRequired: true,
    minStock: 2,
    qty: 4,
    supplier: 0,
    specs: {
      socket: 'LGA1700',
      chipset: 'B760',
      formFactor: 'Micro-ATX',
      ramType: 'DDR4',
      ramSlots: 4,
      maxRamGb: 128,
      m2Slots: 2,
      wifi: true,
    },
    tags: ['ขายดี'],
  },
  {
    sku: 'MB-0003',
    name: 'GIGABYTE B550M K',
    brand: 'GIGABYTE',
    kind: 'mainboard',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 2_490_00,
    regularPriceSatang: 2_790_00,
    costSatang: 2_100_00,
    serialRequired: true,
    minStock: 2,
    qty: 5,
    supplier: 0,
    specs: {
      socket: 'AM4',
      chipset: 'B550',
      formFactor: 'Micro-ATX',
      ramType: 'DDR4',
      ramSlots: 4,
      maxRamGb: 128,
      m2Slots: 1,
      wifi: false,
    },
  },
  {
    sku: 'MB-0004',
    name: 'ASRock B650E PG Riptide WiFi',
    brand: 'ASRock',
    kind: 'mainboard',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 6_590_00,
    costSatang: 5_900_00,
    serialRequired: true,
    minStock: 1,
    qty: 2,
    supplier: 0,
    specs: {
      socket: 'AM5',
      chipset: 'B650E',
      formFactor: 'ATX',
      ramType: 'DDR5',
      ramSlots: 4,
      maxRamGb: 192,
      m2Slots: 3,
      wifi: true,
    },
  },
  {
    sku: 'MB-0005',
    name: 'ASUS ROG STRIX Z790-A GAMING WIFI II',
    brand: 'ASUS',
    kind: 'mainboard',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 12_900_00,
    costSatang: 11_800_00,
    serialRequired: true,
    minStock: 1,
    qty: 1,
    supplier: 0,
    specs: {
      socket: 'LGA1700',
      chipset: 'Z790',
      formFactor: 'ATX',
      ramType: 'DDR5',
      ramSlots: 4,
      maxRamGb: 192,
      m2Slots: 4,
      wifi: true,
    },
    tags: ['สินค้าโชว์'],
  },

  // ---------- RAM ----------
  {
    sku: 'RAM-0001',
    name: 'Kingston FURY Beast DDR5 32GB (2x16) 6000MHz',
    brand: 'Kingston',
    kind: 'ram',
    barcode: '8850003000013',
    warrantyType: D,
    warrantyMonths: 120,
    priceSatang: 3_290_00,
    costSatang: 2_850_00,
    minStock: 4,
    qty: 8,
    supplier: 0,
    specs: { ramType: 'DDR5', capacityGb: 32, modules: 2, speedMhz: 6000, rgb: false },
    tags: ['ขายดี'],
  },
  {
    sku: 'RAM-0002',
    name: 'Kingston FURY Beast DDR4 16GB (2x8) 3200MHz',
    brand: 'Kingston',
    kind: 'ram',
    warrantyType: D,
    warrantyMonths: 120,
    priceSatang: 1_290_00,
    costSatang: 1_050_00,
    minStock: 4,
    qty: 10,
    supplier: 0,
    specs: { ramType: 'DDR4', capacityGb: 16, modules: 2, speedMhz: 3200, rgb: false },
  },
  {
    sku: 'RAM-0003',
    name: 'Corsair Vengeance RGB DDR5 32GB (2x16) 6000MHz',
    brand: 'Corsair',
    kind: 'ram',
    warrantyType: D,
    warrantyMonths: 120,
    priceSatang: 4_190_00,
    regularPriceSatang: 4_590_00,
    costSatang: 3_700_00,
    minStock: 2,
    qty: 4,
    supplier: 0,
    specs: { ramType: 'DDR5', capacityGb: 32, modules: 2, speedMhz: 6000, rgb: true },
  },
  {
    sku: 'RAM-0004',
    name: 'G.SKILL Trident Z5 RGB DDR5 64GB (2x32) 6400MHz',
    brand: 'G.SKILL',
    kind: 'ram',
    warrantyType: D,
    warrantyMonths: 120,
    priceSatang: 8_900_00,
    costSatang: 8_100_00,
    minStock: 1,
    qty: 2,
    supplier: 0,
    specs: { ramType: 'DDR5', capacityGb: 64, modules: 2, speedMhz: 6400, rgb: true },
  },
  {
    sku: 'RAM-0005',
    name: 'Corsair Vengeance LPX DDR4 8GB 3200MHz',
    brand: 'Corsair',
    kind: 'ram',
    warrantyType: D,
    warrantyMonths: 120,
    priceSatang: 690_00,
    costSatang: 520_00,
    minStock: 4,
    qty: 12,
    supplier: 0,
    specs: { ramType: 'DDR4', capacityGb: 8, modules: 1, speedMhz: 3200, rgb: false },
  },
  {
    sku: 'RAM-0006',
    name: 'Kingston ValueRAM DDR4 8GB 2666MHz (มือสอง)',
    brand: 'Kingston',
    kind: 'ram',
    condition: 'used',
    warrantyType: SHOP,
    warrantyMonths: 3,
    supplierWarrantyMonths: 0,
    priceSatang: 450_00,
    costSatang: 300_00,
    minStock: 2,
    qty: 3,
    supplier: 2,
    specs: { ramType: 'DDR4', capacityGb: 8, modules: 1, speedMhz: 2666, rgb: false },
    tags: ['มือสองสภาพดี'],
  },

  // ---------- GPU (serial-tracked) ----------
  {
    sku: 'VGA-0001',
    name: 'ASUS DUAL GeForce RTX 4060 OC 8GB',
    brand: 'ASUS',
    kind: 'gpu',
    barcode: '8850004000011',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 10_900_00,
    costSatang: 9_900_00,
    serialRequired: true,
    minStock: 2,
    qty: 3,
    supplier: 1,
    specs: {
      chipset: 'RTX 4060',
      vramGb: 8,
      gpuPowerWatt: 115,
      lengthMm: 227,
      recommendedPsuWatt: 550,
      powerConnectors: '1x 8-pin',
    },
    tags: ['ขายดี'],
  },
  {
    sku: 'VGA-0002',
    name: 'GIGABYTE GeForce RTX 4070 SUPER WINDFORCE OC 12GB',
    brand: 'GIGABYTE',
    kind: 'gpu',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 22_900_00,
    costSatang: 21_000_00,
    serialRequired: true,
    minStock: 1,
    qty: 2,
    supplier: 1,
    specs: {
      chipset: 'RTX 4070 SUPER',
      vramGb: 12,
      gpuPowerWatt: 220,
      lengthMm: 261,
      recommendedPsuWatt: 650,
      powerConnectors: '1x 16-pin (12VHPWR)',
    },
  },
  {
    sku: 'VGA-0003',
    name: 'SAPPHIRE PULSE Radeon RX 7600 8GB',
    brand: 'SAPPHIRE',
    kind: 'gpu',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 8_490_00,
    regularPriceSatang: 8_990_00,
    costSatang: 7_600_00,
    serialRequired: true,
    minStock: 1,
    qty: 4,
    supplier: 1,
    specs: {
      chipset: 'RX 7600',
      vramGb: 8,
      gpuPowerWatt: 165,
      lengthMm: 204,
      recommendedPsuWatt: 550,
      powerConnectors: '1x 8-pin',
    },
  },
  {
    sku: 'VGA-0004',
    name: 'MSI GeForce RTX 4090 SUPRIM LIQUID X 24GB',
    brand: 'MSI',
    kind: 'gpu',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 79_900_00,
    costSatang: 74_000_00,
    serialRequired: true,
    minStock: 1,
    qty: 0,
    supplier: 1,
    specs: {
      chipset: 'RTX 4090',
      vramGb: 24,
      gpuPowerWatt: 450,
      lengthMm: 356,
      recommendedPsuWatt: 1000,
      powerConnectors: '1x 16-pin (12VHPWR)',
    },
    description: 'สั่งจองล่วงหน้า ของไม่ได้สต็อกไว้',
  },
  {
    sku: 'VGA-0005',
    name: 'ZOTAC GeForce GTX 1650 4GB (มือสอง)',
    brand: 'ZOTAC',
    kind: 'gpu',
    condition: 'used',
    warrantyType: SHOP,
    warrantyMonths: 3,
    supplierWarrantyMonths: 0,
    priceSatang: 2_990_00,
    costSatang: 2_300_00,
    serialRequired: true,
    minStock: 1,
    qty: 1,
    supplier: 2,
    specs: {
      chipset: 'GTX 1650',
      vramGb: 4,
      gpuPowerWatt: 75,
      lengthMm: 151,
      recommendedPsuWatt: 300,
      powerConnectors: 'ไม่ต้องต่อไฟเพิ่ม',
    },
    tags: ['มือสองสภาพดี', 'กล่องไม่สวย'],
  },
  {
    sku: 'VGA-0006',
    name: 'GeForce RTX 3060 12GB (มือสอง รอตั้งราคา)',
    brand: 'Palit',
    kind: 'gpu',
    condition: 'used',
    warrantyType: SHOP,
    warrantyMonths: 3,
    supplierWarrantyMonths: 0,
    priceSatang: null,
    costSatang: 4_500_00,
    serialRequired: true,
    minStock: 0,
    qty: 1,
    supplier: 2,
    specs: {
      chipset: 'RTX 3060',
      vramGb: 12,
      gpuPowerWatt: 170,
      lengthMm: 245,
      recommendedPsuWatt: 550,
      powerConnectors: '1x 8-pin',
    },
    description: 'รับเทิร์นจากลูกค้า รอเจ้าของร้านตั้งราคาขาย',
    tags: ['มือสองสภาพดี'],
  },

  // ---------- Storage ----------
  {
    sku: 'SSD-0001',
    name: 'WD Blue SN580 1TB NVMe',
    brand: 'Western Digital',
    kind: 'storage',
    barcode: '8850005000019',
    warrantyType: D,
    warrantyMonths: 60,
    priceSatang: 1_990_00,
    costSatang: 1_700_00,
    minStock: 4,
    qty: 10,
    supplier: 1,
    specs: {
      storageType: 'NVMe SSD',
      formFactor: 'M.2 2280',
      capacityGb: 1000,
      readMbps: 4150,
      writeMbps: 4150,
    },
    tags: ['ขายดี'],
  },
  {
    sku: 'SSD-0002',
    name: 'Samsung 990 PRO 2TB NVMe',
    brand: 'Samsung',
    kind: 'storage',
    warrantyType: D,
    warrantyMonths: 60,
    priceSatang: 5_290_00,
    costSatang: 4_800_00,
    minStock: 2,
    qty: 3,
    supplier: 1,
    specs: {
      storageType: 'NVMe SSD',
      formFactor: 'M.2 2280',
      capacityGb: 2000,
      readMbps: 7450,
      writeMbps: 6900,
    },
  },
  {
    sku: 'SSD-0003',
    name: 'Kingston NV3 500GB NVMe',
    brand: 'Kingston',
    kind: 'storage',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 1_090_00,
    regularPriceSatang: 1_290_00,
    costSatang: 890_00,
    minStock: 5,
    qty: 12,
    supplier: 1,
    specs: {
      storageType: 'NVMe SSD',
      formFactor: 'M.2 2280',
      capacityGb: 500,
      readMbps: 6000,
      writeMbps: 4000,
    },
  },
  {
    sku: 'SSD-0004',
    name: 'Crucial BX500 480GB SATA SSD',
    brand: 'Crucial',
    kind: 'storage',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 890_00,
    costSatang: 700_00,
    minStock: 4,
    qty: 9,
    supplier: 1,
    specs: {
      storageType: 'SATA SSD',
      formFactor: '2.5"',
      capacityGb: 480,
      readMbps: 540,
      writeMbps: 500,
    },
  },
  {
    sku: 'SSD-0005',
    name: 'Seagate BarraCuda 2TB 3.5"',
    brand: 'Seagate',
    kind: 'storage',
    warrantyType: D,
    warrantyMonths: 24,
    priceSatang: 1_790_00,
    costSatang: 1_550_00,
    minStock: 2,
    qty: 6,
    supplier: 1,
    specs: {
      storageType: 'HDD',
      formFactor: '3.5"',
      capacityGb: 2000,
      readMbps: 220,
      writeMbps: 220,
    },
  },
  {
    sku: 'SSD-0006',
    name: 'WD Purple 4TB 3.5" (สำหรับกล้องวงจรปิด)',
    brand: 'Western Digital',
    kind: 'storage',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 3_490_00,
    costSatang: 3_100_00,
    minStock: 1,
    qty: 2,
    supplier: 1,
    specs: {
      storageType: 'HDD',
      formFactor: '3.5"',
      capacityGb: 4000,
      readMbps: 180,
      writeMbps: 180,
    },
  },

  // ---------- PSU ----------
  {
    sku: 'PSU-0001',
    name: 'Corsair CV650 650W 80+ Bronze',
    brand: 'Corsair',
    kind: 'psu',
    barcode: '8850006000017',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 1_890_00,
    costSatang: 1_600_00,
    minStock: 3,
    qty: 6,
    supplier: 1,
    specs: {
      psuWatt: 650,
      efficiency: '80+ Bronze',
      modular: 'ถอดไม่ได้',
      formFactor: 'ATX',
    },
    tags: ['ขายดี'],
  },
  {
    sku: 'PSU-0002',
    name: 'Seasonic FOCUS GX-850 850W 80+ Gold',
    brand: 'Seasonic',
    kind: 'psu',
    warrantyType: D,
    warrantyMonths: 120,
    priceSatang: 4_290_00,
    costSatang: 3_850_00,
    minStock: 2,
    qty: 3,
    supplier: 1,
    specs: {
      psuWatt: 850,
      efficiency: '80+ Gold',
      modular: 'ถอดได้ทั้งหมด',
      formFactor: 'ATX',
    },
  },
  {
    sku: 'PSU-0003',
    name: 'Cooler Master MWE 550W Bronze V2',
    brand: 'Cooler Master',
    kind: 'psu',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 1_590_00,
    regularPriceSatang: 1_790_00,
    costSatang: 1_350_00,
    minStock: 3,
    qty: 5,
    supplier: 1,
    specs: {
      psuWatt: 550,
      efficiency: '80+ Bronze',
      modular: 'ถอดไม่ได้',
      formFactor: 'ATX',
    },
  },
  {
    sku: 'PSU-0004',
    name: 'Cooler Master V750 SFX Gold',
    brand: 'Cooler Master',
    kind: 'psu',
    warrantyType: D,
    warrantyMonths: 120,
    priceSatang: 4_990_00,
    costSatang: 4_500_00,
    minStock: 1,
    qty: 1,
    supplier: 1,
    specs: {
      psuWatt: 750,
      efficiency: '80+ Gold',
      modular: 'ถอดได้ทั้งหมด',
      formFactor: 'SFX',
    },
  },

  // ---------- Case ----------
  {
    sku: 'CASE-0001',
    name: 'NZXT H5 Flow',
    brand: 'NZXT',
    kind: 'case',
    barcode: '8850007000015',
    warrantyType: D,
    warrantyMonths: 24,
    priceSatang: 2_790_00,
    costSatang: 2_400_00,
    minStock: 2,
    qty: 4,
    supplier: 2,
    specs: {
      supportedFormFactors: ['ATX', 'Micro-ATX', 'Mini-ITX'],
      maxGpuLengthMm: 365,
      maxCoolerHeightMm: 165,
      psuFormFactor: 'ATX',
      includedFans: 2,
    },
  },
  {
    sku: 'CASE-0002',
    name: 'Lian Li LANCOOL 216',
    brand: 'Lian Li',
    kind: 'case',
    warrantyType: D,
    warrantyMonths: 24,
    priceSatang: 3_290_00,
    costSatang: 2_900_00,
    minStock: 2,
    qty: 3,
    supplier: 2,
    specs: {
      supportedFormFactors: ['E-ATX', 'ATX', 'Micro-ATX', 'Mini-ITX'],
      maxGpuLengthMm: 392,
      maxCoolerHeightMm: 180,
      psuFormFactor: 'ATX',
      includedFans: 3,
    },
    tags: ['สินค้าโชว์'],
  },
  {
    sku: 'CASE-0003',
    name: 'Cooler Master MasterBox Q300L',
    brand: 'Cooler Master',
    kind: 'case',
    warrantyType: D,
    warrantyMonths: 24,
    priceSatang: 1_190_00,
    costSatang: 950_00,
    minStock: 3,
    qty: 7,
    supplier: 2,
    specs: {
      supportedFormFactors: ['Micro-ATX', 'Mini-ITX'],
      maxGpuLengthMm: 360,
      maxCoolerHeightMm: 159,
      psuFormFactor: 'ATX',
      includedFans: 1,
    },
  },
  {
    sku: 'CASE-0004',
    name: 'เคสคอมพิวเตอร์ราคาประหยัด รุ่น Elegant',
    brand: 'Tsunami',
    kind: 'case',
    warrantyType: SHOP,
    warrantyMonths: 12,
    supplierWarrantyMonths: 12,
    priceSatang: 690_00,
    costSatang: 520_00,
    minStock: 3,
    qty: 10,
    supplier: 2,
    specs: {
      supportedFormFactors: ['Micro-ATX', 'Mini-ITX'],
      maxGpuLengthMm: 330,
      maxCoolerHeightMm: 155,
      psuFormFactor: 'ATX',
      includedFans: 1,
    },
    tags: ['กล่องไม่สวย'],
  },

  // ---------- Cooler ----------
  {
    sku: 'COOL-0001',
    name: 'DeepCool AK400',
    brand: 'DeepCool',
    kind: 'cooler',
    barcode: '8850008000013',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 990_00,
    costSatang: 800_00,
    minStock: 3,
    qty: 6,
    supplier: 2,
    specs: {
      coolerType: 'ลม (Air)',
      supportedSockets: ['AM4', 'AM5', 'LGA1200', 'LGA1700'],
      heightMm: 155,
      tdpRatingWatt: 220,
    },
    tags: ['ขายดี'],
  },
  {
    sku: 'COOL-0002',
    name: 'Thermalright Peerless Assassin 120 SE',
    brand: 'Thermalright',
    kind: 'cooler',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 1_390_00,
    costSatang: 1_150_00,
    minStock: 2,
    qty: 5,
    supplier: 2,
    specs: {
      coolerType: 'ลม (Air)',
      supportedSockets: ['AM4', 'AM5', 'LGA1200', 'LGA1700', 'LGA1851'],
      heightMm: 155,
      tdpRatingWatt: 265,
    },
  },
  {
    sku: 'COOL-0003',
    name: 'Cooler Master MasterLiquid 240L Core ARGB',
    brand: 'Cooler Master',
    kind: 'cooler',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 2_690_00,
    regularPriceSatang: 2_990_00,
    costSatang: 2_300_00,
    minStock: 1,
    qty: 3,
    supplier: 2,
    specs: {
      coolerType: 'น้ำปิด (AIO)',
      supportedSockets: ['AM4', 'AM5', 'LGA1200', 'LGA1700'],
      heightMm: 52,
      radiatorMm: '240',
      tdpRatingWatt: 250,
    },
  },
  {
    sku: 'COOL-0004',
    name: 'ID-COOLING SE-214-XT ARGB',
    brand: 'ID-COOLING',
    kind: 'cooler',
    warrantyType: D,
    warrantyMonths: 24,
    priceSatang: 590_00,
    costSatang: 450_00,
    minStock: 4,
    qty: 8,
    supplier: 2,
    specs: {
      coolerType: 'ลม (Air)',
      supportedSockets: ['AM4', 'LGA1200', 'LGA1700'],
      heightMm: 150,
      tdpRatingWatt: 180,
    },
  },

  // ---------- Monitor (serial-tracked) ----------
  {
    sku: 'MON-0001',
    name: 'Dell S2425HS 24" IPS 100Hz',
    brand: 'Dell',
    kind: 'monitor',
    barcode: '8850009000011',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 4_290_00,
    costSatang: 3_800_00,
    serialRequired: true,
    minStock: 2,
    qty: 3,
    supplier: 2,
    specs: { sizeInch: 23.8, resolution: '1920x1080', refreshHz: 100, panel: 'IPS', responseMs: 4 },
  },
  {
    sku: 'MON-0002',
    name: 'ASUS TUF Gaming VG27AQ3A 27" QHD 180Hz',
    brand: 'ASUS',
    kind: 'monitor',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 8_990_00,
    costSatang: 8_100_00,
    serialRequired: true,
    minStock: 1,
    qty: 2,
    supplier: 2,
    specs: { sizeInch: 27, resolution: '2560x1440', refreshHz: 180, panel: 'IPS', responseMs: 1 },
    tags: ['ขายดี'],
  },
  {
    sku: 'MON-0003',
    name: 'Samsung Odyssey G5 34" UltraWide 165Hz',
    brand: 'Samsung',
    kind: 'monitor',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 12_900_00,
    regularPriceSatang: 13_900_00,
    costSatang: 11_500_00,
    serialRequired: true,
    minStock: 1,
    qty: 1,
    supplier: 2,
    specs: { sizeInch: 34, resolution: '3440x1440', refreshHz: 165, panel: 'VA', responseMs: 1 },
    tags: ['สินค้าโชว์'],
  },
  {
    sku: 'MON-0004',
    name: 'LG 22MR410 22" 100Hz',
    brand: 'LG',
    kind: 'monitor',
    warrantyType: D,
    warrantyMonths: 36,
    priceSatang: 2_590_00,
    costSatang: 2_200_00,
    serialRequired: true,
    minStock: 2,
    qty: 5,
    supplier: 2,
    specs: { sizeInch: 21.5, resolution: '1920x1080', refreshHz: 100, panel: 'VA', responseMs: 5 },
  },

  // ---------- Accessory ----------
  {
    sku: 'ACC-0001',
    name: 'Logitech G304 LIGHTSPEED (เมาส์ไร้สาย)',
    brand: 'Logitech',
    kind: 'accessory',
    barcode: '8850010000010',
    warrantyType: D,
    warrantyMonths: 24,
    priceSatang: 990_00,
    costSatang: 800_00,
    minStock: 4,
    qty: 10,
    supplier: 3,
    tags: ['ขายดี'],
  },
  {
    sku: 'ACC-0002',
    name: 'Keychron K8 Pro (คีย์บอร์ดไร้สาย)',
    brand: 'Keychron',
    kind: 'accessory',
    warrantyType: D,
    warrantyMonths: 12,
    priceSatang: 3_890_00,
    costSatang: 3_400_00,
    minStock: 1,
    qty: 2,
    supplier: 3,
  },
  {
    sku: 'ACC-0003',
    name: 'Razer BlackWidow V4 X (คีย์บอร์ดเกมมิ่ง)',
    brand: 'Razer',
    kind: 'accessory',
    warrantyType: D,
    warrantyMonths: 24,
    priceSatang: 3_290_00,
    regularPriceSatang: 3_690_00,
    costSatang: 2_900_00,
    minStock: 1,
    qty: 3,
    supplier: 3,
  },
  {
    sku: 'ACC-0004',
    name: 'HyperX Cloud III (หูฟังเกมมิ่ง)',
    brand: 'HyperX',
    kind: 'accessory',
    warrantyType: D,
    warrantyMonths: 24,
    priceSatang: 2_790_00,
    costSatang: 2_400_00,
    minStock: 2,
    qty: 4,
    supplier: 3,
  },
  {
    sku: 'ACC-0005',
    name: 'สาย HDMI 2.1 ยาว 2 เมตร',
    brand: 'Ugreen',
    kind: 'accessory',
    warrantyType: NONE,
    warrantyMonths: 0,
    priceSatang: 290_00,
    costSatang: 180_00,
    minStock: 5,
    qty: 20,
    supplier: 3,
  },
  {
    sku: 'ACC-0006',
    name: 'แผ่นรองเมาส์ขนาดใหญ่ 80x30 ซม.',
    brand: 'Signo',
    kind: 'accessory',
    warrantyType: NONE,
    warrantyMonths: 0,
    priceSatang: 190_00,
    costSatang: 110_00,
    minStock: 5,
    qty: 15,
    supplier: 3,
  },
  {
    sku: 'ACC-0007',
    name: 'ซิลิโคนนำความร้อน Arctic MX-4 (4 กรัม)',
    brand: 'Arctic',
    kind: 'accessory',
    warrantyType: NONE,
    warrantyMonths: 0,
    priceSatang: 350_00,
    costSatang: 250_00,
    minStock: 4,
    qty: 12,
    supplier: 3,
  },
  {
    sku: 'ACC-0008',
    name: 'UPS APC BX950U-MS 950VA',
    brand: 'APC',
    kind: 'accessory',
    warrantyType: D,
    warrantyMonths: 24,
    priceSatang: 2_990_00,
    costSatang: 2_600_00,
    minStock: 1,
    qty: 3,
    supplier: 3,
  },

  // ---------- Service (no stock) ----------
  {
    sku: 'SRV-0001',
    name: 'ค่าบริการประกอบคอมพิวเตอร์',
    brand: '',
    kind: 'service',
    warrantyType: NONE,
    warrantyMonths: 0,
    priceSatang: 500_00,
    costSatang: 0,
    trackStock: false,
    qty: 0,
    supplier: 0,
    description: 'ประกอบเครื่อง ติดตั้งระบบปฏิบัติการ และทดสอบก่อนส่งมอบ',
  },
  {
    sku: 'SRV-0002',
    name: 'ค่าบริการลงโปรแกรม / ลง Windows',
    brand: '',
    kind: 'service',
    warrantyType: NONE,
    warrantyMonths: 0,
    priceSatang: 350_00,
    costSatang: 0,
    trackStock: false,
    qty: 0,
    supplier: 0,
  },
  {
    sku: 'SRV-0003',
    name: 'ค่าบริการทำความสะอาดและเปลี่ยนซิลิโคน',
    brand: '',
    kind: 'service',
    warrantyType: NONE,
    warrantyMonths: 0,
    priceSatang: 400_00,
    costSatang: 0,
    trackStock: false,
    qty: 0,
    supplier: 0,
  },
  {
    sku: 'SRV-0004',
    name: 'ค่าบริการตรวจเช็คอาการเบื้องต้น',
    brand: '',
    kind: 'service',
    warrantyType: NONE,
    warrantyMonths: 0,
    priceSatang: 200_00,
    costSatang: 0,
    trackStock: false,
    qty: 0,
    supplier: 0,
  },

  // ---------- Other ----------
  {
    sku: 'ITEM-0001',
    name: 'คอมพิวเตอร์มือสอง Dell OptiPlex 3070 SFF (i5-9500/8GB/256GB)',
    brand: 'Dell',
    kind: 'other',
    condition: 'used',
    warrantyType: SHOP,
    warrantyMonths: 3,
    supplierWarrantyMonths: 0,
    priceSatang: 5_900_00,
    costSatang: 5_000_00,
    serialRequired: true,
    minStock: 1,
    qty: 2,
    supplier: 2,
    description: 'เครื่องสำนักงานมือสอง สภาพดี พร้อม Windows 11 และประกันร้าน 3 เดือน',
    tags: ['มือสองสภาพดี'],
  },
  {
    sku: 'ITEM-0002',
    name: 'โน้ตบุ๊กมือสอง Lenovo ThinkPad T480 (i5-8250U/8GB/256GB)',
    brand: 'Lenovo',
    kind: 'other',
    condition: 'used',
    warrantyType: SHOP,
    warrantyMonths: 3,
    supplierWarrantyMonths: 0,
    priceSatang: 8_900_00,
    costSatang: 7_800_00,
    serialRequired: true,
    minStock: 1,
    qty: 1,
    supplier: 2,
    tags: ['มือสองสภาพดี'],
  },
];
